spring:
  application:
    name: /meta-service

  datasource:
    url: jdbc:postgresql://localhost:5432/meta-service?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Nurlan2006,
    hikari:
      minimum-idle: 2
      idle-timeout: 40000
      maximum-pool-size: 10
      connection-timeout: 10000
      keepalive-time: 30000
      schema: ${SCHEMA}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog.yaml
    default-schema: public

meta:
  api:
    base-url: https://graph.facebook.com/v25.0
    app-id: ${META_APP_ID}
    app-secret: ${META_APP_SECRET}
    access-token: ${META_PAGE_ACCESS_TOKEN}
    page-id: ${META_PAGE_ID}

