spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/meta-service?currentSchema=public
    username: ${MY_USERNAME}
    password: ${MY_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
